# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# flutter_module 是创建Flutter的模块名称
flutter_application_path = '../flutter_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


target 'NativeAndFlutter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
   # 这边引入
   install_all_flutter_pods(flutter_application_path)

  # Pods for NativeAndFlutter

  target 'NativeAndFlutterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NativeAndFlutterUITests' do
    # Pods for testing
  end

end
